#!/bin/sh

while :; do
	# An already running procd loop must respect a persistent maintenance pause.
	if [ "$(uci -q get autovpn.main.enabled)" = 1 ]; then
		/usr/sbin/autovpnctl refresh >/dev/null
	fi
	interval="$(uci -q get autovpn.main.poll_interval)"
	case "$interval" in
		''|*[!0-9]*) interval=300 ;;
	esac
	[ "$interval" -ge 30 ] 2>/dev/null || interval=30
	sleep "$interval"
done
