#!/bin/sh

while :; do
	/usr/sbin/autovpnctl refresh >/dev/null
	interval="$(uci -q get autovpn.main.poll_interval)"
	case "$interval" in
		''|*[!0-9]*) interval=300 ;;
	esac
	[ "$interval" -ge 30 ] 2>/dev/null || interval=30
	sleep "$interval"
done
